# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: False
  config:
    entity: your_entity
    project: multi-agent-wm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False
    save_dir: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: ${oc.env:STABLEWM_HOME}/outputs/${hydra:job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:STABLEWM_HOME}/multirun/${hydra:job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
